config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do

  end

 
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :edit, :create]

  resources :ideas do
 
     resources :reviews, only: [:create, :destroy]

  end

  # # Routes for IdeasController
  # get "/ideas/new", to: "ideas#new", as: :new_idea
  # post "/ideas", to: "ideas#create", as: :ideas
  # get "/ideas/:id", to: "ideas#show", as: :idea
  # get "/ideas", to: "ideas#index"
  # get "/ideas/:id/edit", to: "ideas#edit", as: :edit_idea
  # patch "/ideas/:id", to: "ideas#update"
  # put "/ideas/:id", to: "ideas#update"
  # delete "/ideas/:id", to: "ideas#destroy"
  
  get('/', { to: 'idea#index', as: 'home' })


end

app/models/ability.rb
class Ability
  include CanCan::Ability


  def initialize(user)

    if user.admin?

      can :manage, :all
    else
      can :read, :all
    end

    can(:delete, Idea) do |idea|

      idea.user == user
    end


    can(:crud, Idea) do |idea|
      user == idea.user
    end

    can(:crud, Review) do |review|
      user == review.user
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
    belongs_to :user

    has_many :reviews, dependent: :destroy
 

    validates(:title, presence: true, uniqueness: true)

  
    validates(
      :description,
      presence: {
        message: "must be given"
      },
      length: {
        minimum: 10,
        maximum: 2048
      }
    )
  
  
    validate :no_monkey
  
    private
  
    def no_monkey

      if description&.downcase&.include?("monkey")
        errors.add(:body, "must not have a monkey")
      end
    end
  end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :idea
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
has_secure_password



has_many :ideas, dependent: :nullify
has_many :reviews, dependent: :nullify

validates :first_name, :last_name, presence: true
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i


validates(
    :email,
    presence: true,
    uniqueness: true,
    format: VALID_EMAIL_REGEX
)

def full_name
  first_name + " " + last_name
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
    def current_user
      if session[:user_id].present?
        @current_user ||= User.find_by(id: session[:user_id])
      end
    end
    helper_method(:current_user)

  
    def user_signed_in?
      current_user.present?
    end
    helper_method :user_signed_in?
  
    def authenticate_user!
      unless current_user.present?
        flash[:danger] = "You must sign in or sign up first!"
        redirect_to new_session_path
      end
    end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :find_idea, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user!, only: [:edit, :update, :destroy]

  def new
    @idea = Idea.new 
  end

  def create
    # render json: params
    @idea = Idea.new idea_params 
    @idea.user = current_user

    if @idea.save
      redirect_to idea_path(@idea.id)
    else
        #render json: idea.errors
      render :new
    end
  end

  def show
    @idea = Idea.find params[:id]
    # render json: @ideas

    @idea.save

    @review = Review.new
    @reviews = @idea.reviews.order(created_at: :desc)
   
  #   # render :show
      #render json:params
  end

  def index
    # @idea = Idea.find params[:id] 
    @ideas = Idea.order(created_at: :desc)
  #   # render json: @ideas
  end

  def edit
    @idea = Idea.find params[:id] 
  end

  def update
    @idea = Idea.find params[:id] 
    if @idea.update(idea_params)
      redirect_to idea_path(@idea.id)
    else
      # render json:params
      render :edit
    end
  end

  def destroy
    @idea.destroy
    redirect_to ideas_path
  end

  private
  def find_idea
    @idea = Idea.find params[:id]
  end

  def idea_params
    params.require(:idea).permit(:title, :description)
  end

  def authorize_user!
    unless can?(:crud, @idea)
      flash[:danger] = "Access Denied"
      redirect_to idea_path(@idea)
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :authenticate_user!
    before_action :authorize_user!, only: [:destroy]
    
    def create
      #render json: parms
      @idea = Idea.find params[:idea_id]
      @review = Review.new review_params
      @review.idea = @idea
      @review.user = current_user
  
      if @review.save
        redirect_to idea_path(@idea)
      else
        @reviews = @idea.reviews.order(created_at: :desc)
        render "ideas/show"
      end
    end
  
    def destroy
      @review ||= Review.find params[:id]
      @review.destroy
  
      redirect_to idea_path(@review.idea)
    end
  
    private
    def review_params
      params.require(:review).permit(:body)
    end
  
    def authorize_user!
      @review = Review.find params[:id]
  
      unless can?(:crud, @review)
        flash[:danger] = "Access Denied!"
        redirect_to idea_path(@review.idea)
      end
    end
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        
    end
  
    def create
      #render json: params
      user = User.find_by(email: params[:session][:email])

      if user&.authenticate(params[:session][:password])
        session[:user_id] = user.id
        flash[:success] = "Success! You are signed in, #{user.first_name}!"
        redirect_to home_path
      else
        flash[:danger] = "Invalid email or password"
        redirect_to home_path
      end
    end
  
    def destroy
      session[:user_id] = nil
      flash[:notice] = 'Signed out!'
      redirect_to home_path
    end

    private
    def session_params
      params.require(:session).permit(:email, :password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
        # render json: parms
    end

    def edit
    end

    def index
    end
    
    def create
#     #render json: params
    @user = User.new user_params

    if @user.save

    session[:user_id] = @user.id
    redirect_to home_path
    
    else
        render :new
    end
    end
    
      private
      def user_params
        params.require(:user).permit(
          :first_name, :last_name, :email, :password, :password_confirmation
        )
      end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.erb
<br clear="all">
<div class="margin50">

<%= form_for(@idea) do |f| %>
    <% if @idea.errors.present? %>
      <p>
        <%= @idea.errors.full_messages.join(', ') %>
      </p>
    <% end %>
    <br clear="all">

    <div>
      <%= f.label(:title) %>
      <%= f.text_field(:title, class: "hundyP") %>
    </div>

    <div class="marginTop">
      <%= f.label(:description) %>
      <%= f.text_area(:description, rows: 6, class: "hundyP") %>
    </div>

    <div class="marginTop">
        <%= f.label(:review) %><br>
        <%= f.text_area(:review, rows: 6, class: "hundyP") %>
    </div>
  
    <%= f.submit(class: "btn btn-outline-primary marginTop") %>
<% end %>

  
   

app/views/ideas/_list.html.erb
<br clear="all">
<div class="margin40">
    <% @ideas.each do |idea| %>
        <div class="container hundyP">
            <div class="card-body hundyP">
                <%= link_to(
                    idea.title,
                    idea_path(idea.id),
                    ) %>
                <p><%= idea.description.truncate(150) %></p>
                <br />
                <small>
                    Posted <%= time_ago_in_words(idea.created_at) %> ago
                </small>
            </div>
        </div>
    <% end %>
</div>

app/views/ideas/edit.html.erb
<h1>Edit Idea</h1>

<%= render "form" %>
<%= link_to "Cancel", idea_path %>

app/views/ideas/index.html.erb
   

    <%= render "list" %>

app/views/ideas/new.html.erb
<h1>Tell us about your new idea!</h1>

<%= render "form" %>

app/views/ideas/show.html.erb
<h2><%= @idea.title %></h2>
<p><%= @idea.description %></p>
<p>By <%= @idea.user&.full_name || "[Deleted]" %></p>
<div>
    <small>
        Posted <%= time_ago_in_words(@idea.created_at) %> ago
    </small>
    •
    <small>
        Last edited <%= time_ago_in_words(@idea.updated_at) %> ago
    </small>
</div>

<div>
    <div class="btn btn-outline-primary">
        <% if user_signed_in? && can?(:edit, @idea) %>
            <small>
                <%= link_to "Edit", edit_idea_path(@idea) %>
            </small>
        <% end %>
    </div>

    <div class="btn btn-outline-primary">
        <% if user_signed_in? && can?(:delete, @idea) %>
            <small>
                <%= link_to "Delete", idea_path(@idea), method: :delete, data: { confirm: "Are you sure?" } %>
            </small>
        <% end %>
        </div>
</div>

<h2>Reviews</h2>
<%= form_for [@idea, @review] do |f| %>

    <% if @review.errors.present? %>
        <p>
            <%= @review.errors.full_messages.join(', ') %>
        </p>
    <% end %>

    <%#= f.hidden_field :idea_id, value: @idea.id %>
 <div>
    <%= f.text_area(
      :body, cols: 60, rows: 6,
      placeholder: "What are your thoughts?"
    ) %>
  </div>

  <%= f.submit "Submit" %>
<% end %>

<div class="review-list">
  	<% @reviews.each do |review| %>
 		<div>
            <p>
                <strong>
                    <%= review.user&.full_name || "[EDITED]" %> reviewed:
                </strong> <br />
                <strong>
                    <%= review.user&.full_name || "[DELETED]" %> reviewed:
                </strong> <br />
                <%= review.body %> <br />
                
                <% if user_signed_in? && can?(:delete, review) %>
                    <div class="btn btn-outline-primary">
                        <small>
                            <%= link_to "Delete", idea_review_path(@idea, review), method: :delete, data: { confirm: "Are you sure you want to delete?" } %>
                        </small>
                    </div>
                <% end %>
                <small>
                    Reviewed <%= time_ago_in_words(review.created_at) %> ago
                </small>
            </p>
    	</div>
  	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav id="myNav" class="navbar navbar-dark bg-light navbar-right hundyP">
        <div class="main">
          <div class="navbar-brand text-primary" href="#!">ideaHUB</div>
            <span class="floatRight">

              <%= link_to 'Ideas', ideas_path %>
              <% if user_signed_in? %>
                <%= link_to 'New Idea', new_idea_path %>


                🤔 Hi, <%= link_to(current_user.first_name, edit_user_path(current_user.id)) %></div>
                |
  
                <%= link_to('Sign Out', session_path, method: :delete) %>
              <% else %>
                <%= link_to('Sign In', new_session_path) %>
                |
                <%= link_to('Sign Up', new_user_path) %>
            
              <% end %>
            </span>
          </div>   
        </div>
    </nav>
    <br clear="all">
    <div class="container-fluid marginTop">
      <% flash.each do |type, message| %>
        <div class="alert alert-<%= type %> alert-dismissible fade show">
          <%= message %>
          <div class="main">
          </div>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<br clear="all">
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <p>
        <%= @user.errors.full_messages.join(', ') %>
      </p>
    <% end %>
  
    <div>
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </div>
  
    <div>
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>
  
    <div>
      <%= f.label :email %>
      <%= f.email_field :email %>
    </div>
  
    <div>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
  
    <div>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>
  
    <%= f.submit "Sign Up"%>
  <% end %>